src/acl/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.RoleListView.as_view(), name="list"),
    url(r'^new/$', views.RoleCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', views.RoleDetailView.as_view(), name="view"),
    url(r'^(?P<pk>\d+)/edit/$', views.RoleUpdateView.as_view(), name="edit"),
]

src/communities/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^$', views.CommunityDetailView.as_view(), name='community'),

    url(r'^search/$', views.CommunitySearchView.as_view(), name='community_search'),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/$', views.UpcomingMeetingView.as_view(), name='committee'),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/publish/$', views.PublishUpcomingView.as_view(),
        name="upcoming_publish"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/start/$', views.StartMeetingView.as_view(),
        name="upcoming_start"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/end/$', views.EndMeetingView.as_view(),
        name="upcoming_end"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/edit-summary/$', views.EditUpcomingSummaryView.as_view(),
        name="upcoming_edit_summary"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/publish/preview/$',
        views.PublishUpcomingMeetingPreviewView.as_view(),
        name='preview_upcoming_meeting'),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/edit/$', views.EditUpcomingMeetingView.as_view(),
        name="upcoming_edit"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/participants/$',
        views.EditUpcomingMeetingParticipantsView.as_view(),
        name="upcoming_edit_participants"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/participants/delete-participant/(?P<participant_id>\d+)/$',
        views.DeleteParticipantView.as_view(),
        name="delete_participant"),

    # FOR TESTING ONLY!
    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/upcoming/sum_votes/$', views.SumVotesView.as_view(),
        name="sum_votes"),

    url(r'^(?P<committee_slug>[a-z0-9_.-]+)/protocol-preview/$',
        views.ProtocolDraftPreviewView.as_view(),
        name='preview_ongoing_protocol'),

]

src/issues/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^$', views.IssueList.as_view(), name="issues"),

    url(r'^create/$', views.IssueCreateView.as_view(), name="issue_create"),

    url(r'^upcoming-create/$', views.IssueCreateView.as_view(upcoming=True), name="issue_create_upcoming"),

    url(r'^(?P<pk>\d+)/$', views.IssueDetailView.as_view(), name="issue"),

    url(r'^(?P<pk>\d+)/edit/$', views.IssueEditView.as_view(), name="issue_edit"),

    url(r'^(?P<pk>\d+)/edit-abstract/$', views.IssueEditAbstractView.as_view(), name="issue_edit_abstract"),

    url(r'^(?P<pk>\d+)/set-length/$', views.IssueSetLengthView.as_view(), name="issue_set_length"),

    url(r'^(?P<pk>\d+)/complete/$', views.IssueCompleteView.as_view(), name="issue_complete"),

    url(r'^(?P<pk>\d+)/delete/$', views.IssueDeleteView.as_view(), name="issue_delete"),

    url(r'^(?P<pk>\d+)/attach/$', views.AttachmentCreateView.as_view(), name="add_attachment"),

    url(r'^(?P<issue_id>\d+)/remove-attachment/(?P<pk>\d+)/$', views.AttachmentDeleteView.as_view(),
        name="attachment_delete"),

    url(r'^(?P<issue_id>\d+)/download-attachment/(?P<pk>\d+)/$', views.AttachmentDownloadView.as_view(),
        name="attachment_download"),

    url(r'^(?P<issue_id>\d+)/create-proposal/$', views.ProposalCreateView.as_view(), name="proposal_create"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/$', views.ProposalDetailView.as_view(), name="proposal"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/edit/$', views.ProposalEditView.as_view(), name="proposal_edit"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/delete/$', views.ProposalDeleteView.as_view(), name="proposal_delete"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/task_completed/$', views.ProposalCompletedTaskView.as_view(),
        name="task_completed"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/edit-task/$', views.ProposalEditTaskView.as_view(), name="proposal_edit_task"),

    url(r'^delete-comment/(?P<pk>\d+)/$', views.IssueCommentDeleteView.as_view(), name="delete_issue_comment"),

    url(r'^edit-comment/(?P<pk>\d+)/$', views.IssueCommentEditView.as_view(), name="edit_issue_comment"),

    url(r'^vote/(?P<pk>\d+)/$', views.ProposalVoteView.as_view(), name="vote_on_proposal"),

    url(r'^vote/(?P<pk>\d+)/multi/$', views.MultiProposalVoteView.as_view(), name="multi_votes_on_proposal"),

    url(r'^argument_vote/(?P<pk>\d+)/$', views.ArgumentRankingVoteView.as_view(), name="vote_on_argument"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/proposal_arguments/$', views.ProposalArgumentsView.as_view(),
        name="proposal_arguments"),

    url(r'^(?P<issue_id>\d+)/(?P<pk>\d+)/proposal_more_arguments/$', views.ProposalMoreArgumentsView.as_view(),
        name="proposal_more_arguments"),

    url(r'^(?P<vote_id>\d+)/vote-argument-create/$', views.ProposalVoteArgumentCreateView.as_view(),
        name="create_vote_argument"),

    url(r'^delete-vote-argument/(?P<pk>\d+)/$', views.ProposalVoteArgumentDeleteView.as_view(),
        name="delete_proposal_argument"),

    url(r'^edit-vote-argument/(?P<pk>\d+)/$', views.ProposalVoteArgumentUpdateView.as_view(),
        name="edit_proposal_argument"),

    url(r'^get-argument-value/(?P<arg_id>\d+)/$', views.get_argument_value, name="get_argument_value"),

    url(r'^argument-up-down-vote/(?P<pk>\d+)/$', views.ArgumentRankingVoteView.as_view(), name="argument_up_down_vote"),

    url(r'^vote_res_panel/(?P<pk>\d+)/$', views.VoteResultsView.as_view(), name="vote_results_panel"),

    url(r'^(?P<issue_id>\d+)/set_register_votes/(?P<pk>\d+)/$', views.ChangeBoardVoteStatusView.as_view(),
        name="set_register_votes"),

    url(r'^autocomplete_tag/$', views.AutoCompleteTagView.as_view(), name="autocomplete_tag"),

    url(r'^assignments/$', views.AssignmentsView.as_view(), name="assignments"),

    url(r'^procedures/$', views.ProceduresView.as_view(), name="procedures"),

]

src/ocd/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset_done, password_reset_confirm, password_reset_complete, logout
from django.core.urlresolvers import reverse_lazy
from django.views.i18n import javascript_catalog
from django.views.static import serve
from meetings.views import MeetingCreateView
from ocd.views import login_user
from users.forms import OCPasswordResetForm, OCPasswordResetConfirmForm
from users.models import CODE_LENGTH
from users.views import AcceptInvitationView, oc_password_reset
import communities.views

js_info_dict = {
    'packages': ('issues', 'communities'),
}

urlpatterns = [

    url(r'^$', communities.views.LandingPage.as_view(), name='landing'),

    url(r'^communities/$', communities.views.CommunityList.as_view(), name='home'),

    url(r'^about/$', communities.views.About.as_view(), name='about'),

    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/roles/', include('acl.urls', namespace="role")),
    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/members/', include('users.urls')),
    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/groups/',
        include('communities.group_urls', namespace="group")),
    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/groups-role/',
        include('communities.group_role_urls', namespace="group_role")),
    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/', include('communities.urls')),

    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/(?P<committee_slug>[a-z][a-z0-9-]+)/upcoming/close/$',
        MeetingCreateView.as_view(), name="upcoming_close"),

    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/(?P<committee_slug>[a-z][a-z0-9-]+)/issues/',
        include('issues.urls')),
    url(r'^c/(?P<community_slug>[a-z][a-z0-9-]+)/(?P<committee_slug>[a-z][a-z0-9-]+)/history/',
        include('meetings.urls')),

    url(r'^login/$', login_user, {'template_name': 'login.html'}, name="login"),

    url(r'^logout/$', logout, {'next_page': reverse_lazy('home')},
        name="logout"),

    url(r'^invitation/(?P<code>[a-z0-9]{%d})/$' % CODE_LENGTH, AcceptInvitationView.as_view(),
        name="accept_invitation"),

    url(r'^user/password/reset/$', oc_password_reset,
        {'post_reset_redirect': '/user/password/reset/done/', 'password_reset_form': OCPasswordResetForm},
        name="password_reset"),
    url(r'^user/password/reset/done/$', password_reset_done),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': '/user/password/done/', 'set_password_form': OCPasswordResetConfirmForm}),
    url(r'^user/password/done/$', password_reset_complete),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^django-rq/', include('django_rq.urls')),

    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

src/meetings/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.formats import date_format
from django.utils.translation import ugettext_lazy as _
from issues.models import Issue, ProposalStatus
from ocd.base_models import UIDMixin, HTMLField, ConfidentialByRelationMixin
from ocd.base_managers import ConfidentialManager
from acl.default_roles import DefaultGroups


class AgendaItemManager(ConfidentialManager):
    """Manage queries over AgendaItem."""


@python_2_unicode_compatible
class AgendaItem(ConfidentialByRelationMixin):
    confidential_from = 'issue'
    objects = ConfidentialManager()
    meeting = models.ForeignKey('Meeting', on_delete=models.CASCADE, verbose_name=_("Meeting"), related_name="agenda")
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, verbose_name=_("Issue"), related_name="agenda_items")
    background = HTMLField(_("Background"), null=True, blank=True)
    order = models.PositiveIntegerField(default=100, verbose_name=_("Order"))
    closed = models.BooleanField(_('Closed'), default=True)

    class Meta:
        unique_together = (("meeting", "issue"),)
        verbose_name = _("Agenda Item")
        verbose_name_plural = _("Agenda Items")
        ordering = ('meeting__created_at', 'order')

    def __str__(self):
        return self.issue.title

        # def natural_key(self):

    # return (self.meeting.natural_key(), self.issue.natural_key())
    # natural_key.dependencies = ['meetings.meeting', 'issues.issue']

    def attachments(self):
        return self.issue.attachments.filter(agenda_item=self)

    def comments(self):
        return self.issue.comments.filter(active=True, meeting=self.meeting)

    def proposals(self, user=None, committee=None):
        rv = self.issue.proposals.object_access_control(
            user=user, committee=committee).filter(
            active=True, decided_at_meeting=self.meeting)
        return rv

    def accepted_proposals(self, user=None, committee=None):
        rv = self.proposals(user=user, committee=committee).filter(status=ProposalStatus.ACCEPTED)
        return rv

    def rejected_proposals(self, user=None, committee=None):
        rv = self.proposals(user=user, committee=committee).filter(status=ProposalStatus.REJECTED)
        return rv


@python_2_unicode_compatible
class Meeting(UIDMixin):
    # community = models.ForeignKey('communities.Community', related_name="meetings", verbose_name=_("Community"))
    committee = models.ForeignKey('communities.Committee', on_delete=models.CASCADE, related_name="meetings", verbose_name=_("Committee"), null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="meetings_created",
                                   on_delete=models.CASCADE,
                                   verbose_name=_("Created by"))
    held_at = models.DateTimeField(_("Held at"))
    title = models.CharField(_("Title"), max_length=300, null=True, blank=True)
    scheduled_at = models.DateTimeField(_("Scheduled at"), null=True, blank=True)
    location = models.CharField(_("Location"), max_length=300, null=True, blank=True)
    comments = models.TextField(_("Comments"), null=True, blank=True)
    summary = models.TextField(_("Summary"), null=True, blank=True)
    agenda_items = models.ManyToManyField(Issue, through=AgendaItem,
                                          blank=True,
                                          related_name='meetings',
                                          verbose_name=_("Agenda items"))
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                          related_name="participated_in_meeting",
                                          verbose_name=_("Participants"),
                                          through='MeetingParticipant')
    guests = models.TextField(_("Guests"), null=True, blank=True, help_text=_("Enter each guest in a separate line"))

    class Meta:
        verbose_name = _("Meeting")
        verbose_name_plural = _("Meetings")
        ordering = ("-held_at", )

    def __str__(self):
        s = date_format(self.held_at)
        if self.title:
            s += " - " + self.title
        return s
        # return date_format(self.scheduled_at) + ", " + time_format(self.scheduled_at)

    # NEED TO FILTER THE QUERYSET AT RUNTIME FOR CONFIDENTIAL.
    # THIS METHOD IS NOT SAFE TO USE DIRECTLY ANYMORE
    # def get_active_issues(self):
    # return [ai.issue for ai in self.agenda.all() if ai.issue.active]

    def get_guest_list(self):
        if not self.guests:
            return []
        return filter(None, [s.strip() for s in self.guests.splitlines()])

    def get_title_or_date(self):
        return self.title or date_format(self.held_at)

    def get_title_or_shortdate(self):
        return self.title or self.held_at.strftime('%d/%m/%Y')

    def get_title_and_shortdate(self):
        if self.title:
            return self.held_at.strftime('%d/%m/%Y') + " - " + self.title
        else:
            return self.held_at.strftime('%d/%m/%Y')

    def get_participations(self):
        return self.participations.filter(is_absent=False)

    def get_participants(self):
        participations = self.get_participations()
        return [p.user for p in participations]

    def meeting_participants(self):
        meeting_participants = {'board': [], 'members': [], }
        board_ids = [m.user.id for m in self.committee.community.memberships.board()]
        for p in self.get_participations():
            if p.user.id in board_ids:
                meeting_participants['board'].append(p.user)
            else:
                meeting_participants['members'].append(p.user)

        # doing it simply like this, as I'd need to refactor models
        # just to order in the way that is now required.
        for index, item in enumerate(meeting_participants['board']):
            if item.get_default_group(self.committee.community) == DefaultGroups.CHAIRMAN:
                meeting_participants['board'].insert(0, meeting_participants['board'].pop(index))
        return meeting_participants

    @models.permalink
    def get_absolute_url(self):
        return "meeting", (self.committee.community.slug, self.committee.slug, str(self.pk))


class BoardParticipantsManager(models.Manager):
    def board(self):
        return self.get_queryset().exclude(default_group_name=DefaultGroups.MEMBER, is_absent=True)


@python_2_unicode_compatible
class MeetingParticipant(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, verbose_name=_("Meeting"), related_name="participations")
    ordinal = models.PositiveIntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="participations")
    # denormalize for history :
    display_name = models.CharField(_("Name"), max_length=200)
    default_group_name = models.CharField(_('Group'), max_length=50,
                                          choices=DefaultGroups.CHOICES,
                                          null=True, blank=True)
    is_absent = models.BooleanField(_("Is Absent"), default=False)
    objects = BoardParticipantsManager()

    class Meta:
        verbose_name = _("Meeting Participant")
        verbose_name_plural = _("Meeting Participants")
        unique_together = (('meeting', 'ordinal'), ('meeting', 'user'))

    def __str__(self):
        return self.user.display_name


# def natural_key(self):
# return (self.meeting.natural_key(), self.user.natural_key())
#     natural_key.dependencies = ['meetings.meeting', 'users.ocuser']


@python_2_unicode_compatible
class MeetingExternalParticipant(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, verbose_name=_("Meeting"))
    name = models.CharField(max_length=200, verbose_name=_("Name"))

    class Meta:
        verbose_name = _("Meeting External Participant")
        verbose_name_plural = _("Meeting External Participants")

    def __str__(self):
        return self.name

#     def natural_key(self):
#         return (self.meetings.natural_key(), self.name)
#     natural_key.dependencies = ['meetings.meeting']

src/communities/templates/communities/_additional_issue.html
{% load i18n %}
{% load opencommunity voting_tags %}

<li class="issue oc_li" data-issue="{{i.id}}">
	<div class="available-issue-date">
		{{ i.created_at|ocshortdate }}
	</div>
	<a href="{{i.get_absolute_url}}"{% if not object.upcoming_meeting_is_published %} style="margin-{% if LANGUAGE_CODE == 'he' %}left{% else %}right{% endif %}: 100px;"{% endif %}>
		{{i.title}}
	</a>

	{% if 'editagenda_community' in cperms and not i.changed_in_current and not i.completed %}
		<div class="timer{% if not object.upcoming_meeting_started and i.is_upcoming %} timer_extra{% endif %}" data-url="{% url 'issue_set_length' community.id i.id %}">
			<span data-strict="{{i.length_in_minutes|minutes_strict}}">{{i.length_in_minutes|minutes|default:'--:--'}}</span>
    </div>
    {% if not object.upcoming_meeting_started and i.is_upcoming and i.can_straw_vote %}
    <div class="user_votes_on_issue">
      {% user_votes_on_issue %}
    </div>
    {% endif %}
		<div class="icon-plus-minus agenda_plus_minus">
			<a href="#" class="addremove"></a>
		</div>
	{% else %} 
		{% if i.can_straw_vote and 'vote' in cperms and user.id and not object.upcoming_meeting_started and i.is_upcoming %}
			<div class="user_votes_on_issue">
				{% user_votes_on_issue %}
			</div>
		{% endif %}
		{% if object.upcoming_meeting_started %}
			<div class="agenda_plus_minus
			{% if i.completed and 'view_update_status' in cperms %}tick{% else %}
			{% if i.changed_in_current and 'view_update_status' in cperms %}cog{% endif %}
			{% endif %}"></div>
		{% endif %}
	{% endif %}
</li>

src/communities/templates/communities/_my_community.html
{% for m in user.memberships.all %}

    {% ifchanged m.community %}
        {% if not forloop.first %}
            </a></li>
        {% endif %}
        <li class="left_arrow oc_li">
        <a href="{{ m.community.get_absolute_url }}">
        {% if m.community.is_public %}
            <img class="ui-li-icon" src="{{ STATIC_URL }}images/world.png" width="16" height="16"/>
        {% else %}
            <img class="ui-li-icon" src="{{ STATIC_URL }}images/lock.png" width="16" height="16"/>
        {% endif %}

        <b>{{ m.community.name }}</b>

        {% if m.get_default_group_name_display %}
            ({{ m.get_default_group_name_display }})
        {% endif %}
    {% else %}
        {% if m.get_default_group_name_display %}
            ({{ m.get_default_group_name_display }})
        {% endif %}
    {% endifchanged %}

{% endfor %}
</a></li>

src/communities/templates/communities/base_meeting.html
{% extends "base.html" %}
{% load i18n %}
{% load opencommunity community_tags %}

{% block extra-page-id %}
	id="upcoming-meeting"
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="meeting_right_column col-sm-3 hidden-xs">
	<h2>
		<span style="text-decoration: underline; display: block;">{{ committee.name }}</span>
        {% if LANGUAGE_CODE == 'he' and committee.no_meetings_community %}
        {% trans "Updates" %}
        {% else %}
        {% trans "Meetings" %}
        {% endif %}
    </h2>
  	<ul class="meetings_list">
    {% comment %} show upcoming meeting entry only if published or the current user has permission to view the draft {% endcomment %}
    {% if community.upcoming_meeting_is_published or 'viewupcoming_draft' in cperms %}
		<li>
			{% if object == committee %} <div class="pull-right" style="width: 15px;"><span class="active_meeting pull-right"></span></div>{% endif %}
			<a href="{{ committee.get_absolute_url }}">
                {% if LANGUAGE_CODE == 'he' and committee.no_meetings_community %}
				{{committee.upcoming_meeting_title|default:_("Next update")}}
                {% else %}
				{{committee.upcoming_meeting_title|default:_("Upcoming Meeting")}}
                {% endif %}
				{% if committee.upcoming_meeting_scheduled_at %}<br /><span style="font-size: 11px;">{{ committee.upcoming_meeting_scheduled_at|date:"d F, Y" }}</span>{% endif %}
			</a>
    	</li>
    {% endif %}
	{% if committee.meetings.count %}
		{% for i in committee.meetings.all %}
		<li>
			{% if object == i %} <div class="pull-right" style="width: 15px;"><span class="active_meeting pull-right"></span></div>{% endif %}
			<a href="{{ i.get_absolute_url }}">
				{{ i.get_title_or_shortdate }}
				{% if i.title and i.held_at %}<br /><span style="font-size: 11px;">{{ i.held_at|date:"d F, Y" }}</span>{% endif %}
			</a>
		</li>
		{% endfor %}
	{% endif %}
	</ul>
</div>

<div class="meeting_left_column col-sm-9 col-xs-12">
{% block meeting %}
{% endblock %}
</div>

{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/typeahead.js-bootstrap.css"/>
{% endblock %}

{% block jquiscript %}
<script src="{{STATIC_URL}}jquery-ui/js/jquery-ui-1.10.2.custom.js"></script>
{% endblock %}

{% block scripts %}
<script src="{{STATIC_URL}}js/jquery.ui.touch-punch.js"></script>
<script src="{{STATIC_URL}}js/upcoming.js"></script>
<script src="{{STATIC_URL}}bootstrap/js/typeahead.min.js"></script>
<script src="{{STATIC_URL}}js/hogan-2.0.0.js"></script>
<script src="{{STATIC_URL}}js/issues.js"></script>

<script>
    $(function() {
        $('input.issue-search').bind('input', function() {
            searchIssues($(this).val().trim(), $(this));
        });
    });
</script>
{% block additional_scripts %}{% endblock %}
{% endblock %}

src/communities/templates/communities/community.html
{% extends "base.html" %}
{% load i18n opencommunity community_tags %}

{% block extra-page-id %}
    id="community"
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
    <div class="row">
    {% for c in committees %}
        <div class="col-xs-12">
            <h4>
                <a href="{{ c.committee.get_absolute_url }}">{{ c.committee.name }}</a>
            </h4>
        </div>
        {% if 'viewupcoming_community' in cperms %}
        <div class="col-xs-12 col-sm-4 committee-meeting">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ c.committee.get_absolute_url }}">{{ c.committee.upcoming_meeting_title|default_if_none:_("Upcoming meeting") }}</a>
                    <small class="pull-right">{{ c.committee|display_upcoming_time }}</small>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                    {% if c.issues %}
                    {% for issue in c.issues %}
                        <a href="{{ issue.get_absolute_url }}" class="list-group-item">{{ issue }}</a>
                    {% endfor %}
                    {% else %}
                    <p class="list-group-item">{% trans 'No upcoming issues' %}</p>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% for m in c.meetings %}
        <div class="col-xs-12 col-sm-4 committee-meeting">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ m.get_absolute_url }}">{{ m.get_title_or_shortdate }}</a>
                    <small class="pull-right">{{ m.held_at|date:"d F, Y" }}</small>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                    {% if m.issues %}
                    {% for issue in m.issues %}
                        <a href="{{ issue.get_absolute_url }}" class="list-group-item">{{ issue }}</a>
                    {% endfor %}
                    {% else %}
                    {% trans 'No issues' %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endfor %}
    </div>
{% endblock %}

src/communities/templates/communities/communitygroup_form.html
{% extends "dialog.html" %}
{% load i18n %}

{% block page_header %}
    {% trans "Create new group" %}
{% endblock %}

{% block content %}

    {{ form }}

    <a class="btn btn-oc" role="button" data-toggle="collapse" href="#groupRoleForm" aria-expanded="false" aria-controls="groupRoleForm">
        <i class="fa fa-plus"></i> {% trans 'Assign to committee' %}
    </a>
    <div class="collapse" id="groupRoleForm">
        {{ form.group_role }}
    </div>
{% endblock %}

src/communities/templates/communities/communitygrouprole_detail.html
{% extends "base.html" %}
{% load i18n opencommunity %}

{% block page_header %} {{ object.committee.name }} &gt; {{ object.group.title }} &gt; {{ object.role.title }}{% endblock %}


{% block content %}

    <a class="btn btn-oc" data-rel="form" href="{% url 'group_role:update' community.slug object.id %}">{% trans "Edit" %}</a>

{% endblock %}

src/communities/templates/communities/communitygrouprole_list.html
{% extends "base.html" %}
{% load i18n opencommunity %}

{% block page_header %} {% trans "Groups" %} {% endblock %}


{% block content %}

    {% if object_list %}

        <table class="groups table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Committee' %}</th>
                    <th>{% trans 'Group' %}</th>
                    <th>{% trans 'Role' %}</th>
                </tr>
            </thead>
            </tbody>
            {% for c in object_list %}
                <tr>
                    <td>
                        <a href="{{ c.get_absolute_url }}">{{ c.committee.name }}</a>
                    </td>
                    <td>{{ c.group.title }}</td>
                    <td>{{ c.role.title }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}

    <a class="btn btn-oc" data-rel="form" href="{% url 'group_role:create' community.slug %}">{% trans "Create Group Role" %}</a>

{% endblock %}